name: vprofile actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-EKS

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: set java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Setup Sonarqube
        uses: warden/setup-sonar-scanner@v7

      - name: Sonarqube scanner
        run: sonar-scanner \
          -Dsonar.host.url=${{secrets.SONAR_URL}} \
          -Dsonar.login=${{secrets.SONAR_TOKEN}} \
          -Dsonar.organization=${{secrets.SONAR_ORGANIZATION}} \
          -Dsonar.projectKey=${{secrets.SONAR_PROJECT_KEY}} \
          -Dsonar.sources=src/ \
          -Dsonar.junit.reportPath=target/surefire-reports/ \
          -Dsonar.jacoco.reportPaths=target/jacoco.exec \
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml\
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

      - name: Sonar Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONARQUBE_HOST_URL: ${{secrets.SONAR_URL}}
          SONARQUBE_TOKEN: ${{secrets.SONAR_TOKEN}}
